modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Configurable%20Extra%20Mob%20Drops"
logoFile="icon.png"

[[mods]]
modId="configurableextramobdrops"
version="3.2"
displayName="Configurable Extra Mob Drops"
displayURL="https://serilum.com/mod/configurable-extra-mob-drops"
authors="Rick South"
description='''Add extra drops to any (modded) mob entity via commands and a config file.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.configurableextramobdrops]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.configurableextramobdrops]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"